#!/usr/bin/env python3
"""Verify that public/sitemap.xml is well-formed and contains the expected static routes."""

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

_PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

from services.sitemap import STATIC_ROUTES  # noqa: E402

SITEMAP_PATH = _PROJECT_ROOT / "public" / "sitemap.xml"
NAMESPACE = "http://www.sitemaps.org/schemas/sitemap/0.9"
# Derived from the single source of truth so this stays in sync automatically.
MIN_URLS = len(STATIC_ROUTES)


def main() -> None:
    if not SITEMAP_PATH.exists():
        print(f"ERROR: {SITEMAP_PATH} not found", file=sys.stderr)
        sys.exit(1)

    # xml.etree is safe here: the file is generated by our own code moments
    # earlier in the same CI step — it is not untrusted external input, so
    # defusedxml provides no practical security benefit.
    try:
        tree = ET.parse(SITEMAP_PATH)
    except ET.ParseError as exc:
        print(f"ERROR: sitemap is not valid XML: {exc}", file=sys.stderr)
        sys.exit(1)

    root = tree.getroot()
    urls = root.findall(f"{{{NAMESPACE}}}url")

    if len(urls) < MIN_URLS:
        print(
            f"ERROR: expected at least {MIN_URLS} URLs, got {len(urls)}",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"✅ Sitemap valid: {len(urls)} URL(s)")


if __name__ == "__main__":
    main()
